CREATE TABLE AGENT_DECISION (
  ID NUMBER(19) PRIMARY KEY,
  MESSAGE_ID NUMBER(19) NOT NULL,
  ATTACHMENT_ID NUMBER(19),
  PROVIDER VARCHAR2(64) NOT NULL,
  MODEL VARCHAR2(255) NOT NULL,
  LATENCY_MS NUMBER(19) DEFAULT 0 NOT NULL,
  FALLBACK_USED VARCHAR2(5) DEFAULT 'false' NOT NULL,
  FALLBACK_REASON VARCHAR2(2000),
  ROUTING_JSON CLOB,
  ANSWERS_JSON CLOB,
  DECISION_JSON CLOB NOT NULL,
  CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE SEQUENCE AGENT_DECISION_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE INDEX IX_AGENT_DECISION_MESSAGE
  ON AGENT_DECISION (MESSAGE_ID, CREATED_AT);

CREATE INDEX IX_AGENT_DECISION_PROVIDER
  ON AGENT_DECISION (PROVIDER, CREATED_AT);
