CREATE TABLE AGENT_RUNTIME_STATE (
  ID NUMBER(10) PRIMARY KEY,
  STATUS VARCHAR2(32) NOT NULL,
  POLICY_VERSION VARCHAR2(128) NOT NULL,
  UPDATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_BY VARCHAR2(255) NOT NULL
);

INSERT INTO AGENT_RUNTIME_STATE (ID, STATUS, POLICY_VERSION, UPDATED_BY)
VALUES (1, 'RUNNING', 'pv-1', 'migration');

CREATE TABLE AGENT_JOB (
  ID NUMBER(19) PRIMARY KEY,
  MESSAGE_ID NUMBER(19) NOT NULL,
  STATE VARCHAR2(40) NOT NULL,
  ATTEMPT_COUNT NUMBER(10) DEFAULT 0 NOT NULL,
  LAST_ERROR VARCHAR2(2000),
  POLICY_VERSION VARCHAR2(128) NOT NULL,
  CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  STARTED_AT TIMESTAMP(6),
  COMPLETED_AT TIMESTAMP(6),
  CONSTRAINT UK_AGENT_JOB_MESSAGE UNIQUE (MESSAGE_ID)
);

CREATE SEQUENCE AGENT_JOB_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE TABLE AGENT_EVENT (
  ID NUMBER(19) PRIMARY KEY,
  JOB_ID NUMBER(19),
  MESSAGE_ID NUMBER(19) NOT NULL,
  EVENT_TYPE VARCHAR2(80) NOT NULL,
  FROM_STATE VARCHAR2(40),
  TO_STATE VARCHAR2(40),
  ACTOR_TYPE VARCHAR2(40) NOT NULL,
  ACTOR_ID VARCHAR2(255),
  DETAILS_JSON CLOB,
  CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE SEQUENCE AGENT_EVENT_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE INDEX IX_AGENT_JOB_STATE ON AGENT_JOB (STATE, UPDATED_AT);
CREATE INDEX IX_AGENT_EVENT_MESSAGE ON AGENT_EVENT (MESSAGE_ID, CREATED_AT);
